[package]
name = "background"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.13"
rfd = "0.15.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
tray-icon = "0.14.3"
winit = "0.29.15"
