[package]
name = "background"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
rfd = "0.14.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.125"
tray-icon = "0.14.3"
winit = "0.30.5"
