[package]
name = "background"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
rfd = "0.14.1"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
tray-icon = "0.13.4"
winit = "0.29.15"
