[package]
name = "background"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
rfd = "0.15.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tray-icon = "0.14.3"
winit = "0.30.5"
