name: Rust CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run cargo fmt --check
        run: cargo fmt -- --check
      - name: Run cargo check
        run: cargo check
